#!/bin/bash

while getopts ":e:" opt; do
  case $opt in
    e)
      skip_flags=(${OPTARG//,/ })
      echo ${skip_flags[@]}
      shift $((OPTIND-1))
      ;;
    \?)
      echo "Script usage: $(basename \$0) [-e except tags delimited by ,]" >&2
      exit 1
      ;;
  esac
done

# Check if bump.cfg exists in the current directory
cfg_file="bump.cfg"
if [[ ! -f "$cfg_file" ]]; then
  echo "bump.cfg file not found in the current directory."
  exit 1
fi

# Read bump.cfg file line by line
while IFS="@" read -r file tag flag; do

  if [ ! -z $flag ]; then
    if printf '%s\0' "${skip_flags[@]}" | grep -Fxqz -- $flag; then
      echo "Flag $flag skipped. Skipping $file."
      continue
    fi  
  fi

  echo $file $tag

  if [ ! -f "$file" ]; then
    echo "File $file not found. Skipping."
    continue
  fi

  # Increment version number on the line containing the specified tag
  sed -i -r -E "s/^($tag) (\"?).*/\1 \2$1\2/" "$file" || echo "Failed to update version $tag in $file."

done < "$cfg_file"

echo "Version bumping completed."
